// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class BoardingRecord
{
    public long BoardingRecordId { get; set; }

    public long BookingSeatId { get; set; }

    public long TripStopId { get; set; }

    public long ScannedByUserId { get; set; }

    public string Status { get; set; }

    public DateTime? ScannedAtUtc { get; set; }

    public virtual BookingSeat BookingSeat { get; set; }

    public virtual User ScannedByUser { get; set; }

    public virtual TripStop TripStop { get; set; }
}