// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Booking
{
    public long BookingId { get; set; }

    public string BookingReference { get; set; }

    public long UserId { get; set; }

    public long TripId { get; set; }

    public long BoardingTripStopId { get; set; }

    public long DroppingTripStopId { get; set; }

    public DateTime? BookedAtUtc { get; set; }

    public string CurrencyCode { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? ServiceFee { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime? CancelledAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual TripStop BoardingTripStop { get; set; }

    public virtual ICollection<BookingPassenger> BookingPassengers { get; set; } = new List<BookingPassenger>();

    public virtual ICollection<BookingSeat> BookingSeats { get; set; } = new List<BookingSeat>();

    public virtual ICollection<BookingTransfer> BookingTransfers { get; set; } = new List<BookingTransfer>();

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual ICollection<CouponUsage> CouponUsages { get; set; } = new List<CouponUsage>();

    public virtual ICollection<DisruptionAffectedBooking> DisruptionAffectedBookings { get; set; } = new List<DisruptionAffectedBooking>();

    public virtual TripStop DroppingTripStop { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<OfferUsage> OfferUsages { get; set; } = new List<OfferUsage>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<PaymentTransfer> PaymentTransfers { get; set; } = new List<PaymentTransfer>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Refund> Refunds { get; set; } = new List<Refund>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<SeatHold> SeatHolds { get; set; } = new List<SeatHold>();

    public virtual ICollection<SettlementItem> SettlementItems { get; set; } = new List<SettlementItem>();

    public virtual Trip Trip { get; set; }

    public virtual User User { get; set; }
}