// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Bus
{
    public long BusId { get; set; }

    public long OperatorId { get; set; }

    public long BusTypeId { get; set; }

    public string RegistrationNumber { get; set; }

    public string Manufacturer { get; set; }

    public string Model { get; set; }

    public long SeatLayoutId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual BusType BusType { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual SeatLayout SeatLayout { get; set; }

    public virtual ICollection<TripBuse> TripBuses { get; set; } = new List<TripBuse>();
}