// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Complaint
{
    public long ComplaintId { get; set; }

    public long BookingId { get; set; }

    public long UserId { get; set; }

    public long OperatorId { get; set; }

    public string Category { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public long AssignedToUserId { get; set; }

    public string ResolutionNotes { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? ResolvedAtUtc { get; set; }

    public virtual User AssignedToUser { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual User User { get; set; }
}