// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class DisruptionAffectedBooking
{
    public long DisruptionAffectedBookingId { get; set; }

    public long OperatorDisruptionId { get; set; }

    public long BookingId { get; set; }

    public decimal? PassengerRefundPercent { get; set; }

    public decimal? PenaltyAmount { get; set; }

    public string ResolutionStatus { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual OperatorDisruption OperatorDisruption { get; set; }
}