// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Driver
{
    public long DriverId { get; set; }

    public long OperatorId { get; set; }

    public long UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PhoneNumber { get; set; }

    public string LicenseNumberMasked { get; set; }

    public DateOnly? LicenseExpiresOn { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual ICollection<TripStaffAssignment> TripStaffAssignments { get; set; } = new List<TripStaffAssignment>();

    public virtual User User { get; set; }
}