// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Notification
{
    public long NotificationId { get; set; }

    public long UserId { get; set; }

    public long BookingId { get; set; }

    public string Channel { get; set; }

    public long TemplateId { get; set; }

    public string Destination { get; set; }

    public string PayloadJson { get; set; }

    public string Status { get; set; }

    public DateTime? ScheduledAtUtc { get; set; }

    public DateTime? SentAtUtc { get; set; }

    public long? ProviderMessageId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual NotificationTemplate Template { get; set; }

    public virtual User User { get; set; }
}