// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class OfferUsage
{
    public long OfferUsageId { get; set; }

    public long OfferId { get; set; }

    public long UserId { get; set; }

    public long BookingId { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime? UsedAtUtc { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Offer Offer { get; set; }

    public virtual User User { get; set; }
}