// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class OperatorPenalty
{
    public long OperatorPenaltyId { get; set; }

    public long OperatorId { get; set; }

    public long TripId { get; set; }

    public long DisruptionId { get; set; }

    public string ReasonCode { get; set; }

    public int? AffectedPassengerCount { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual OperatorDisruption Disruption { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual Trip Trip { get; set; }
}