// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class OperatorDisruption
{
    public long OperatorDisruptionId { get; set; }

    public long TripId { get; set; }

    public long OperatorId { get; set; }

    public string DisruptionType { get; set; }

    public string Reason { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public string Status { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<DisruptionAffectedBooking> DisruptionAffectedBookings { get; set; } = new List<DisruptionAffectedBooking>();

    public virtual Operator Operator { get; set; }

    public virtual ICollection<OperatorPenalty> OperatorPenalties { get; set; } = new List<OperatorPenalty>();

    public virtual Trip Trip { get; set; }
}