// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Operator
{
    public long OperatorId { get; set; }

    public string LegalName { get; set; }

    public string DisplayName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string BusinessType { get; set; }

    public string Pan { get; set; }

    public string Gstin { get; set; }

    public string Address { get; set; }

    public string KycStatus { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual ICollection<Conductor> Conductors { get; set; } = new List<Conductor>();

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    public virtual ICollection<OperatorBankAccount> OperatorBankAccounts { get; set; } = new List<OperatorBankAccount>();

    public virtual ICollection<OperatorDisruption> OperatorDisruptions { get; set; } = new List<OperatorDisruption>();

    public virtual ICollection<OperatorDocument> OperatorDocuments { get; set; } = new List<OperatorDocument>();

    public virtual ICollection<OperatorPenalty> OperatorPenalties { get; set; } = new List<OperatorPenalty>();

    public virtual ICollection<OperatorSettlement> OperatorSettlements { get; set; } = new List<OperatorSettlement>();

    public virtual ICollection<OperatorUser> OperatorUsers { get; set; } = new List<OperatorUser>();

    public virtual ICollection<PaymentProviderAccount> PaymentProviderAccounts { get; set; } = new List<PaymentProviderAccount>();

    public virtual ICollection<PaymentTransfer> PaymentTransfers { get; set; } = new List<PaymentTransfer>();

    public virtual ICollection<PricingRule> PricingRules { get; set; } = new List<PricingRule>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<SeatLayout> SeatLayouts { get; set; } = new List<SeatLayout>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}