// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class OperatorUser
{
    public long OperatorUserId { get; set; }

    public long OperatorId { get; set; }

    public long UserId { get; set; }

    public bool? IsPrimary { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual User User { get; set; }
}