// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class PaymentProviderAccount
{
    public long PaymentProviderAccountId { get; set; }

    public long OperatorId { get; set; }

    public string ProviderName { get; set; }

    public long? ExternalAccountId { get; set; }

    public string KycStatus { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Operator Operator { get; set; }
}