// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class PaymentTransfer
{
    public long PaymentTransferId { get; set; }

    public long PaymentId { get; set; }

    public long BookingId { get; set; }

    public long OperatorId { get; set; }

    public decimal? Amount { get; set; }

    public long? ProviderTransferId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? SettledAtUtc { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual ICollection<SettlementItem> SettlementItems { get; set; } = new List<SettlementItem>();
}