// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Refund
{
    public long RefundId { get; set; }

    public long BookingId { get; set; }

    public long PaymentId { get; set; }

    public decimal? RequestedAmount { get; set; }

    public decimal? ApprovedAmount { get; set; }

    public string ReasonCode { get; set; }

    public long? ProviderRefundId { get; set; }

    public string Status { get; set; }

    public DateTime? RequestedAtUtc { get; set; }

    public DateTime? ProcessedAtUtc { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Payment Payment { get; set; }
}