// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Review
{
    public long ReviewId { get; set; }

    public long BookingId { get; set; }

    public long UserId { get; set; }

    public long OperatorId { get; set; }

    public long TripId { get; set; }

    public byte? Rating { get; set; }

    public string ReviewText { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual Trip Trip { get; set; }

    public virtual User User { get; set; }
}