// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class RouteStop
{
    public long RouteStopId { get; set; }

    public long RouteId { get; set; }

    public long StopId { get; set; }

    public int? SequenceNo { get; set; }

    public int? ScheduledOffsetMinutes { get; set; }

    public string BoardingAllowed { get; set; }

    public string DroppingAllowed { get; set; }

    public string RestStop { get; set; }

    public int? DefaultStopDurationMinutes { get; set; }

    public virtual Route Route { get; set; }

    public virtual Stop Stop { get; set; }

    public virtual ICollection<TripStop> TripStops { get; set; } = new List<TripStop>();
}