// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Route
{
    public long RouteId { get; set; }

    public long OperatorId { get; set; }

    public string RouteName { get; set; }

    public long OriginStopId { get; set; }

    public long DestinationStopId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Stop DestinationStop { get; set; }

    public virtual Operator Operator { get; set; }

    public virtual Stop OriginStop { get; set; }

    public virtual ICollection<PricingRule> PricingRules { get; set; } = new List<PricingRule>();

    public virtual ICollection<RouteStop> RouteStops { get; set; } = new List<RouteStop>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}