// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class SeatHold
{
    public long SeatHoldId { get; set; }

    public long TripSeatInventoryId { get; set; }

    public long UserId { get; set; }

    public long BookingId { get; set; }

    public string HoldToken { get; set; }

    public DateTime? HeldAtUtc { get; set; }

    public DateTime? ExpiresAtUtc { get; set; }

    public string Status { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual TripSeatInventory TripSeatInventory { get; set; }

    public virtual User User { get; set; }
}