// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class SeatLayoutSeat
{
    public long SeatLayoutSeatId { get; set; }

    public long SeatLayoutId { get; set; }

    public string SeatCode { get; set; }

    public string SeatType { get; set; }

    public string Deck { get; set; }

    public short? RowNumber { get; set; }

    public short? ColumnNumber { get; set; }

    public int? PositionFlags { get; set; }

    public bool? IsBookable { get; set; }

    public virtual SeatLayout SeatLayout { get; set; }

    public virtual ICollection<TripSeatInventory> TripSeatInventories { get; set; } = new List<TripSeatInventory>();
}