// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class TripFare
{
    public long TripFareId { get; set; }

    public long TripId { get; set; }

    public long FromTripStopId { get; set; }

    public long ToTripStopId { get; set; }

    public string SeatType { get; set; }

    public decimal? BaseFare { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalFare { get; set; }

    public string CurrencyCode { get; set; }

    public virtual TripStop FromTripStop { get; set; }

    public virtual TripStop ToTripStop { get; set; }

    public virtual Trip Trip { get; set; }
}