// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class TripSeatInventory
{
    public long TripSeatInventoryId { get; set; }

    public long TripId { get; set; }

    public long SeatLayoutSeatId { get; set; }

    public string SeatCodeSnapshot { get; set; }

    public string SeatTypeSnapshot { get; set; }

    public string DeckSnapshot { get; set; }

    public string Status { get; set; }

    public string BlockedReason { get; set; }

    public virtual ICollection<BookingSeat> BookingSeats { get; set; } = new List<BookingSeat>();

    public virtual ICollection<SeatHold> SeatHolds { get; set; } = new List<SeatHold>();

    public virtual SeatLayoutSeat SeatLayoutSeat { get; set; }

    public virtual Trip Trip { get; set; }
}