// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class Trip
{
    public long TripId { get; set; }

    public long OperatorId { get; set; }

    public long RouteId { get; set; }

    public DateOnly? ServiceDate { get; set; }

    public DateTime? OriginDepartureAtLocal { get; set; }

    public long? OriginTimeZoneId { get; set; }

    public string TripCode { get; set; }

    public DateTime? BookingOpenAtUtc { get; set; }

    public DateTime? BookingCloseAtUtc { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual ICollection<BookingTransfer> BookingTransferFromTrips { get; set; } = new List<BookingTransfer>();

    public virtual ICollection<BookingTransfer> BookingTransferToTrips { get; set; } = new List<BookingTransfer>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Operator Operator { get; set; }

    public virtual ICollection<OperatorDisruption> OperatorDisruptions { get; set; } = new List<OperatorDisruption>();

    public virtual ICollection<OperatorPenalty> OperatorPenalties { get; set; } = new List<OperatorPenalty>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Route Route { get; set; }

    public virtual ICollection<TripBuse> TripBuses { get; set; } = new List<TripBuse>();

    public virtual ICollection<TripFare> TripFares { get; set; } = new List<TripFare>();

    public virtual ICollection<TripSeatInventory> TripSeatInventories { get; set; } = new List<TripSeatInventory>();

    public virtual ICollection<TripStaffAssignment> TripStaffAssignments { get; set; } = new List<TripStaffAssignment>();

    public virtual ICollection<TripStop> TripStops { get; set; } = new List<TripStop>();
}