// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class TripStaffAssignment
{
    public long TripStaffAssignmentId { get; set; }

    public long TripId { get; set; }

    public long DriverId { get; set; }

    public long ConductorId { get; set; }

    public DateTime? AssignedAtUtc { get; set; }

    public DateTime? ContactReleaseAtUtc { get; set; }

    public string Status { get; set; }

    public virtual Conductor Conductor { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual Trip Trip { get; set; }
}