// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class TripStop
{
    public long TripStopId { get; set; }

    public long TripId { get; set; }

    public long RouteStopId { get; set; }

    public int? SequenceNo { get; set; }

    public DateTime? ArrivalAtLocal { get; set; }

    public DateTime? DepartureAtLocal { get; set; }

    public long? TimeZoneId { get; set; }

    public string BoardingAllowed { get; set; }

    public string DroppingAllowed { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BoardingRecord> BoardingRecords { get; set; } = new List<BoardingRecord>();

    public virtual ICollection<Booking> BookingBoardingTripStops { get; set; } = new List<Booking>();

    public virtual ICollection<Booking> BookingDroppingTripStops { get; set; } = new List<Booking>();

    public virtual ICollection<BookingSeat> BookingSeatFromTripStops { get; set; } = new List<BookingSeat>();

    public virtual ICollection<BookingSeat> BookingSeatToTripStops { get; set; } = new List<BookingSeat>();

    public virtual RouteStop RouteStop { get; set; }

    public virtual Trip Trip { get; set; }

    public virtual ICollection<TripFare> TripFareFromTripStops { get; set; } = new List<TripFare>();

    public virtual ICollection<TripFare> TripFareToTripStops { get; set; } = new List<TripFare>();
}