// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class TripBuse
{
    public long TripBusId { get; set; }

    public long TripId { get; set; }

    public long BusId { get; set; }

    public string RegistrationNumberSnapshot { get; set; }

    public DateTime? AssignedAtUtc { get; set; }

    public DateTime? BusNumberAllocatedAtUtc { get; set; }

    public bool? IsPrimary { get; set; }

    public string Status { get; set; }

    public string ReplacementReason { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual Trip Trip { get; set; }
}