// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApniSavari.Infrastructure.Persistence.Context.Persistence.Entities;

public partial class ApniSavariDbContext : DbContext
{
    public ApniSavariDbContext(DbContextOptions<ApniSavariDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Amenity> Amenities { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<BoardingRecord> BoardingRecords { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingPassenger> BookingPassengers { get; set; }

    public virtual DbSet<BookingSeat> BookingSeats { get; set; }

    public virtual DbSet<BookingTransfer> BookingTransfers { get; set; }

    public virtual DbSet<Bus> Buses { get; set; }

    public virtual DbSet<BusAmenity> BusAmenities { get; set; }

    public virtual DbSet<BusType> BusTypes { get; set; }

    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<Conductor> Conductors { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponUsage> CouponUsages { get; set; }

    public virtual DbSet<DisruptionAffectedBooking> DisruptionAffectedBookings { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<MediaFile> MediaFiles { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<NotificationTemplate> NotificationTemplates { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<OfferUsage> OfferUsages { get; set; }

    public virtual DbSet<Operator> Operators { get; set; }

    public virtual DbSet<OperatorBankAccount> OperatorBankAccounts { get; set; }

    public virtual DbSet<OperatorDisruption> OperatorDisruptions { get; set; }

    public virtual DbSet<OperatorDocument> OperatorDocuments { get; set; }

    public virtual DbSet<OperatorPenalty> OperatorPenalties { get; set; }

    public virtual DbSet<OperatorSettlement> OperatorSettlements { get; set; }

    public virtual DbSet<OperatorUser> OperatorUsers { get; set; }

    public virtual DbSet<Passenger> Passengers { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentProviderAccount> PaymentProviderAccounts { get; set; }

    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }

    public virtual DbSet<PaymentTransfer> PaymentTransfers { get; set; }

    public virtual DbSet<PricingRule> PricingRules { get; set; }

    public virtual DbSet<Refund> Refunds { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Route> Routes { get; set; }

    public virtual DbSet<RouteStop> RouteStops { get; set; }

    public virtual DbSet<SeatHold> SeatHolds { get; set; }

    public virtual DbSet<SeatLayout> SeatLayouts { get; set; }

    public virtual DbSet<SeatLayoutSeat> SeatLayoutSeats { get; set; }

    public virtual DbSet<SettlementItem> SettlementItems { get; set; }

    public virtual DbSet<Stop> Stops { get; set; }

    public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripBuse> TripBuses { get; set; }

    public virtual DbSet<TripFare> TripFares { get; set; }

    public virtual DbSet<TripSeatInventory> TripSeatInventories { get; set; }

    public virtual DbSet<TripStaffAssignment> TripStaffAssignments { get; set; }

    public virtual DbSet<TripStop> TripStops { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserTravelPreference> UserTravelPreferences { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Amenity>(entity =>
        {
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(200);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasIndex(e => new { e.EntityName, e.EntityId, e.CreatedAtUtc }, "IX_AuditLogs_Entity_Time");

            entity.Property(e => e.Action).HasMaxLength(255);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.EntityName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IpAddress)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.UserAgent).HasMaxLength(1000);

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuditLogs_UserId_Users");
        });

        modelBuilder.Entity<BoardingRecord>(entity =>
        {
            entity.Property(e => e.ScannedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.BookingSeat).WithMany(p => p.BoardingRecords)
                .HasForeignKey(d => d.BookingSeatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BoardingRecords_BookingSeatId_BookingSeats");

            entity.HasOne(d => d.ScannedByUser).WithMany(p => p.BoardingRecords)
                .HasForeignKey(d => d.ScannedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BoardingRecords_ScannedByUserId_Users");

            entity.HasOne(d => d.TripStop).WithMany(p => p.BoardingRecords)
                .HasForeignKey(d => d.TripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BoardingRecords_TripStopId_TripStops");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasIndex(e => new { e.TripId, e.Status }, "IX_Bookings_Trip_Status");

            entity.HasIndex(e => new { e.UserId, e.BookedAtUtc }, "IX_Bookings_User_BookedAt");

            entity.HasIndex(e => e.BookingReference, "UX_Bookings_BookingReference").IsUnique();

            entity.Property(e => e.BookedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.BookingReference).HasMaxLength(255);
            entity.Property(e => e.CancelledAtUtc).HasPrecision(3);
            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ServiceFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.BoardingTripStop).WithMany(p => p.BookingBoardingTripStops)
                .HasForeignKey(d => d.BoardingTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_BoardingTripStopId_TripStops");

            entity.HasOne(d => d.DroppingTripStop).WithMany(p => p.BookingDroppingTripStops)
                .HasForeignKey(d => d.DroppingTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_DroppingTripStopId_TripStops");

            entity.HasOne(d => d.Trip).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_TripId_Trips");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_UserId_Users");
        });

        modelBuilder.Entity<BookingPassenger>(entity =>
        {
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPassengers)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPassengers_BookingId_Bookings");

            entity.HasOne(d => d.Passenger).WithMany(p => p.BookingPassengers)
                .HasForeignKey(d => d.PassengerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPassengers_PassengerId_Passengers");
        });

        modelBuilder.Entity<BookingSeat>(entity =>
        {
            entity.HasIndex(e => new { e.TripSeatInventoryId, e.FromTripStopId, e.ToTripStopId }, "IX_BookingSeats_Inventory_From_To");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FareAmount).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingSeats)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSeats_BookingId_Bookings");

            entity.HasOne(d => d.BookingPassenger).WithMany(p => p.BookingSeats)
                .HasForeignKey(d => d.BookingPassengerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSeats_BookingPassengerId_BookingPassengers");

            entity.HasOne(d => d.FromTripStop).WithMany(p => p.BookingSeatFromTripStops)
                .HasForeignKey(d => d.FromTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSeats_FromTripStopId_TripStops");

            entity.HasOne(d => d.ToTripStop).WithMany(p => p.BookingSeatToTripStops)
                .HasForeignKey(d => d.ToTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSeats_ToTripStopId_TripStops");

            entity.HasOne(d => d.TripSeatInventory).WithMany(p => p.BookingSeats)
                .HasForeignKey(d => d.TripSeatInventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSeats_TripSeatInventoryId_TripSeatInventory");
        });

        modelBuilder.Entity<BookingTransfer>(entity =>
        {
            entity.Property(e => e.CompletedAtUtc).HasPrecision(3);
            entity.Property(e => e.Reason).HasMaxLength(255);
            entity.Property(e => e.RequestedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.TransferFee).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingTransfers)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingTransfers_BookingId_Bookings");

            entity.HasOne(d => d.FromTrip).WithMany(p => p.BookingTransferFromTrips)
                .HasForeignKey(d => d.FromTripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingTransfers_FromTripId_Trips");

            entity.HasOne(d => d.ToTrip).WithMany(p => p.BookingTransferToTrips)
                .HasForeignKey(d => d.ToTripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingTransfers_ToTripId_Trips");
        });

        modelBuilder.Entity<Bus>(entity =>
        {
            entity.HasIndex(e => e.RegistrationNumber, "UX_Buses_RegistrationNumber").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Manufacturer).HasMaxLength(255);
            entity.Property(e => e.Model).HasMaxLength(255);
            entity.Property(e => e.RegistrationNumber)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.BusType).WithMany(p => p.Buses)
                .HasForeignKey(d => d.BusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Buses_BusTypeId_BusTypes");

            entity.HasOne(d => d.Operator).WithMany(p => p.Buses)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Buses_OperatorId_Operators");

            entity.HasOne(d => d.SeatLayout).WithMany(p => p.Buses)
                .HasForeignKey(d => d.SeatLayoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Buses_SeatLayoutId_SeatLayouts");
        });

        modelBuilder.Entity<BusAmenity>(entity =>
        {
            entity.HasKey(e => e.AmenityId);
        });

        modelBuilder.Entity<BusType>(entity =>
        {
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(200);
        });

        modelBuilder.Entity<Complaint>(entity =>
        {
            entity.Property(e => e.Category)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.ResolutionNotes).HasMaxLength(4000);
            entity.Property(e => e.ResolvedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.Subject).HasMaxLength(500);

            entity.HasOne(d => d.AssignedToUser).WithMany(p => p.ComplaintAssignedToUsers)
                .HasForeignKey(d => d.AssignedToUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaints_AssignedToUserId_Users");

            entity.HasOne(d => d.Booking).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaints_BookingId_Bookings");

            entity.HasOne(d => d.Operator).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaints_OperatorId_Operators");

            entity.HasOne(d => d.User).WithMany(p => p.ComplaintUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaints_UserId_Users");
        });

        modelBuilder.Entity<Conductor>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.Conductors)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Conductors_OperatorId_Operators");

            entity.HasOne(d => d.User).WithMany(p => p.Conductors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Conductors_UserId_Users");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasIndex(e => e.Code, "UX_Coupons_Code").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.DiscountType).HasMaxLength(255);
            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EndsAtUtc).HasPrecision(3);
            entity.Property(e => e.FirstBookingOnly).HasMaxLength(255);
            entity.Property(e => e.MaxDiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinBookingAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PerUserUsageLimit).HasMaxLength(255);
            entity.Property(e => e.StartsAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UsageLimit).HasMaxLength(255);
        });

        modelBuilder.Entity<CouponUsage>(entity =>
        {
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UsedAtUtc).HasPrecision(3);

            entity.HasOne(d => d.Booking).WithMany(p => p.CouponUsages)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CouponUsages_BookingId_Bookings");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CouponUsages)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CouponUsages_CouponId_Coupons");

            entity.HasOne(d => d.User).WithMany(p => p.CouponUsages)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CouponUsages_UserId_Users");
        });

        modelBuilder.Entity<DisruptionAffectedBooking>(entity =>
        {
            entity.Property(e => e.PassengerRefundPercent).HasColumnType("decimal(9, 4)");
            entity.Property(e => e.PenaltyAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ResolutionStatus).HasMaxLength(255);

            entity.HasOne(d => d.Booking).WithMany(p => p.DisruptionAffectedBookings)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DisruptionAffectedBookings_BookingId_Bookings");

            entity.HasOne(d => d.OperatorDisruption).WithMany(p => p.DisruptionAffectedBookings)
                .HasForeignKey(d => d.OperatorDisruptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DisruptionAffectedBookings_OperatorDisruptionId_OperatorDisruptions");
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.LicenseNumberMasked)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.Drivers)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drivers_OperatorId_Operators");

            entity.HasOne(d => d.User).WithMany(p => p.Drivers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drivers_UserId_Users");
        });

        modelBuilder.Entity<MediaFile>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FileType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MimeType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.OriginalFileName).HasMaxLength(500);
            entity.Property(e => e.OwnerType).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.StorageKey).HasMaxLength(1000);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.MediaFiles)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaFiles_CreatedByUserId_Users");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasIndex(e => new { e.Status, e.ScheduledAtUtc }, "IX_Notifications_Status_Scheduled");

            entity.Property(e => e.Channel)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Destination).HasMaxLength(255);
            entity.Property(e => e.ScheduledAtUtc).HasPrecision(3);
            entity.Property(e => e.SentAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_BookingId_Bookings");

            entity.HasOne(d => d.Template).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_TemplateId_NotificationTemplates");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_UserId_Users");
        });

        modelBuilder.Entity<NotificationTemplate>(entity =>
        {
            entity.HasKey(e => e.TemplateId);

            entity.Property(e => e.Channel)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SubjectTemplate).HasMaxLength(500);
            entity.Property(e => e.TemplateCode)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Offer>(entity =>
        {
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.DiscountType).HasMaxLength(255);
            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EndsAtUtc).HasPrecision(3);
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.StartsAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
        });

        modelBuilder.Entity<OfferUsage>(entity =>
        {
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UsedAtUtc).HasPrecision(3);

            entity.HasOne(d => d.Booking).WithMany(p => p.OfferUsages)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferUsages_BookingId_Bookings");

            entity.HasOne(d => d.Offer).WithMany(p => p.OfferUsages)
                .HasForeignKey(d => d.OfferId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferUsages_OfferId_Offers");

            entity.HasOne(d => d.User).WithMany(p => p.OfferUsages)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferUsages_UserId_Users");
        });

        modelBuilder.Entity<Operator>(entity =>
        {
            entity.Property(e => e.Address).HasMaxLength(1000);
            entity.Property(e => e.BusinessType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.Gstin)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("GSTIN");
            entity.Property(e => e.KycStatus).HasMaxLength(255);
            entity.Property(e => e.LegalName).HasMaxLength(200);
            entity.Property(e => e.Pan)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("PAN");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
        });

        modelBuilder.Entity<OperatorBankAccount>(entity =>
        {
            entity.Property(e => e.AccountHolderName).HasMaxLength(255);
            entity.Property(e => e.AccountNumberMasked)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.BankName).HasMaxLength(255);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Ifsc)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("IFSC");
            entity.Property(e => e.VerificationStatus).HasMaxLength(255);

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorBankAccounts)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorBankAccounts_OperatorId_Operators");
        });

        modelBuilder.Entity<OperatorDisruption>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DisruptionType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Reason).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.OperatorDisruptions)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorDisruptions_CreatedByUserId_Users");

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorDisruptions)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorDisruptions_OperatorId_Operators");

            entity.HasOne(d => d.Trip).WithMany(p => p.OperatorDisruptions)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorDisruptions_TripId_Trips");
        });

        modelBuilder.Entity<OperatorDocument>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DocumentNumber).HasMaxLength(255);
            entity.Property(e => e.DocumentType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FileUrl).HasMaxLength(1000);
            entity.Property(e => e.RejectionReason).HasMaxLength(1000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VerifiedAtUtc).HasPrecision(3);

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorDocuments)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorDocuments_OperatorId_Operators");

            entity.HasOne(d => d.VerifiedByUser).WithMany(p => p.OperatorDocuments)
                .HasForeignKey(d => d.VerifiedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorDocuments_VerifiedByUserId_Users");
        });

        modelBuilder.Entity<OperatorPenalty>(entity =>
        {
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReasonCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Disruption).WithMany(p => p.OperatorPenalties)
                .HasForeignKey(d => d.DisruptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorPenalties_DisruptionId_OperatorDisruptions");

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorPenalties)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorPenalties_OperatorId_Operators");

            entity.HasOne(d => d.Trip).WithMany(p => p.OperatorPenalties)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorPenalties_TripId_Trips");
        });

        modelBuilder.Entity<OperatorSettlement>(entity =>
        {
            entity.HasIndex(e => new { e.OperatorId, e.Status }, "IX_OperatorSettlements_Operator_Status");

            entity.HasIndex(e => e.SettlementReference, "UX_OperatorSettlements_SettlementReference").IsUnique();

            entity.Property(e => e.AdjustmentAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CommissionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EligibleAtUtc).HasPrecision(3);
            entity.Property(e => e.GrossAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PenaltyAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SettledAtUtc).HasPrecision(3);
            entity.Property(e => e.SettlementReference).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorSettlements)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorSettlements_OperatorId_Operators");
        });

        modelBuilder.Entity<OperatorUser>(entity =>
        {
            entity.HasIndex(e => new { e.OperatorId, e.UserId }, "UX_OperatorUsers_Operator_User").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.OperatorUsers)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorUsers_OperatorId_Operators");

            entity.HasOne(d => d.User).WithMany(p => p.OperatorUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OperatorUsers_UserId_Users");
        });

        modelBuilder.Entity<Passenger>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.Passengers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Passengers_UserId_Users");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Method)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ProviderName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ProviderSignatureVerified).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.Payments)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_BookingId_Bookings");
        });

        modelBuilder.Entity<PaymentProviderAccount>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.KycStatus).HasMaxLength(255);
            entity.Property(e => e.ProviderName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.PaymentProviderAccounts)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentProviderAccounts_OperatorId_Operators");
        });

        modelBuilder.Entity<PaymentTransaction>(entity =>
        {
            entity.HasIndex(e => new { e.BookingId, e.OccurredAtUtc }, "IX_PaymentTransactions_Booking_Time");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OccurredAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.TransactionType)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Booking).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransactions_BookingId_Bookings");

            entity.HasOne(d => d.Payment).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransactions_PaymentId_Payments");
        });

        modelBuilder.Entity<PaymentTransfer>(entity =>
        {
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.SettledAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.PaymentTransfers)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransfers_BookingId_Bookings");

            entity.HasOne(d => d.Operator).WithMany(p => p.PaymentTransfers)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransfers_OperatorId_Operators");

            entity.HasOne(d => d.Payment).WithMany(p => p.PaymentTransfers)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransfers_PaymentId_Payments");
        });

        modelBuilder.Entity<PricingRule>(entity =>
        {
            entity.Property(e => e.CommissionPercent).HasColumnType("decimal(9, 4)");
            entity.Property(e => e.EffectiveFromUtc).HasMaxLength(255);
            entity.Property(e => e.EffectiveToUtc).HasMaxLength(255);
            entity.Property(e => e.SeatType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ServiceFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.PricingRules)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PricingRules_OperatorId_Operators");

            entity.HasOne(d => d.Route).WithMany(p => p.PricingRules)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PricingRules_RouteId_Routes");
        });

        modelBuilder.Entity<Refund>(entity =>
        {
            entity.Property(e => e.ApprovedAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProcessedAtUtc).HasPrecision(3);
            entity.Property(e => e.ReasonCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.RequestedAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RequestedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.Refunds)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refunds_BookingId_Bookings");

            entity.HasOne(d => d.Payment).WithMany(p => p.Refunds)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refunds_PaymentId_Payments");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReviewText).HasMaxLength(2000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_BookingId_Bookings");

            entity.HasOne(d => d.Operator).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_OperatorId_Operators");

            entity.HasOne(d => d.Trip).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_TripId_Trips");

            entity.HasOne(d => d.User).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_UserId_Users");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasIndex(e => e.RoleName, "UX_Roles_RoleName").IsUnique();

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RoleName).HasMaxLength(255);
        });

        modelBuilder.Entity<Route>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.RouteName).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.DestinationStop).WithMany(p => p.RouteDestinationStops)
                .HasForeignKey(d => d.DestinationStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Routes_DestinationStopId_Stops");

            entity.HasOne(d => d.Operator).WithMany(p => p.Routes)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Routes_OperatorId_Operators");

            entity.HasOne(d => d.OriginStop).WithMany(p => p.RouteOriginStops)
                .HasForeignKey(d => d.OriginStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Routes_OriginStopId_Stops");
        });

        modelBuilder.Entity<RouteStop>(entity =>
        {
            entity.HasIndex(e => new { e.RouteId, e.SequenceNo }, "UX_RouteStops_Route_Sequence").IsUnique();

            entity.Property(e => e.BoardingAllowed).HasMaxLength(255);
            entity.Property(e => e.DroppingAllowed).HasMaxLength(255);
            entity.Property(e => e.RestStop).HasMaxLength(255);

            entity.HasOne(d => d.Route).WithMany(p => p.RouteStops)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RouteStops_RouteId_Routes");

            entity.HasOne(d => d.Stop).WithMany(p => p.RouteStops)
                .HasForeignKey(d => d.StopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RouteStops_StopId_Stops");
        });

        modelBuilder.Entity<SeatHold>(entity =>
        {
            entity.HasIndex(e => new { e.TripSeatInventoryId, e.ExpiresAtUtc, e.Status }, "IX_SeatHolds_Inventory_Expiry");

            entity.HasIndex(e => e.HoldToken, "UX_SeatHolds_HoldToken").IsUnique();

            entity.Property(e => e.ExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.HeldAtUtc).HasPrecision(3);
            entity.Property(e => e.HoldToken)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Booking).WithMany(p => p.SeatHolds)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeatHolds_BookingId_Bookings");

            entity.HasOne(d => d.TripSeatInventory).WithMany(p => p.SeatHolds)
                .HasForeignKey(d => d.TripSeatInventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeatHolds_TripSeatInventoryId_TripSeatInventory");

            entity.HasOne(d => d.User).WithMany(p => p.SeatHolds)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeatHolds_UserId_Users");
        });

        modelBuilder.Entity<SeatLayout>(entity =>
        {
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Operator).WithMany(p => p.SeatLayouts)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeatLayouts_OperatorId_Operators");
        });

        modelBuilder.Entity<SeatLayoutSeat>(entity =>
        {
            entity.HasIndex(e => new { e.SeatLayoutId, e.SeatCode }, "UX_SeatLayoutSeats_Layout_SeatCode").IsUnique();

            entity.Property(e => e.Deck)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SeatCode)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SeatType)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.SeatLayout).WithMany(p => p.SeatLayoutSeats)
                .HasForeignKey(d => d.SeatLayoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeatLayoutSeats_SeatLayoutId_SeatLayouts");
        });

        modelBuilder.Entity<SettlementItem>(entity =>
        {
            entity.Property(e => e.AdjustmentAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CommissionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GrossAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PenaltyAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.SettlementItems)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SettlementItems_BookingId_Bookings");

            entity.HasOne(d => d.OperatorSettlement).WithMany(p => p.SettlementItems)
                .HasForeignKey(d => d.OperatorSettlementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SettlementItems_OperatorSettlementId_OperatorSettlements");

            entity.HasOne(d => d.PaymentTransfer).WithMany(p => p.SettlementItems)
                .HasForeignKey(d => d.PaymentTransferId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SettlementItems_PaymentTransferId_PaymentTransfers");
        });

        modelBuilder.Entity<Stop>(entity =>
        {
            entity.Property(e => e.Address).HasMaxLength(1000);
            entity.Property(e => e.City).HasMaxLength(255);
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.StateCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
        });

        modelBuilder.Entity<SystemConfiguration>(entity =>
        {
            entity.HasKey(e => e.ConfigurationId);

            entity.Property(e => e.ConfigurationKey)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.DataType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.UpdatedByUser).WithMany(p => p.SystemConfigurations)
                .HasForeignKey(d => d.UpdatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SystemConfigurations_UpdatedByUserId_Users");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasIndex(e => new { e.RouteId, e.ServiceDate, e.Status }, "IX_Trips_Route_ServiceDate_Status");

            entity.Property(e => e.BookingCloseAtUtc).HasPrecision(3);
            entity.Property(e => e.BookingOpenAtUtc).HasPrecision(3);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.OriginDepartureAtLocal).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.TripCode)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.Operator).WithMany(p => p.Trips)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_OperatorId_Operators");

            entity.HasOne(d => d.Route).WithMany(p => p.Trips)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_RouteId_Routes");
        });

        modelBuilder.Entity<TripBuse>(entity =>
        {
            entity.HasKey(e => e.TripBusId);

            entity.Property(e => e.AssignedAtUtc).HasPrecision(3);
            entity.Property(e => e.BusNumberAllocatedAtUtc).HasPrecision(3);
            entity.Property(e => e.RegistrationNumberSnapshot).HasMaxLength(255);
            entity.Property(e => e.ReplacementReason).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Bus).WithMany(p => p.TripBuses)
                .HasForeignKey(d => d.BusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripBuses_BusId_Buses");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripBuses)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripBuses_TripId_Trips");
        });

        modelBuilder.Entity<TripFare>(entity =>
        {
            entity.Property(e => e.BaseFare).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CurrencyCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.SeatType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalFare).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.FromTripStop).WithMany(p => p.TripFareFromTripStops)
                .HasForeignKey(d => d.FromTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripFares_FromTripStopId_TripStops");

            entity.HasOne(d => d.ToTripStop).WithMany(p => p.TripFareToTripStops)
                .HasForeignKey(d => d.ToTripStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripFares_ToTripStopId_TripStops");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripFares)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripFares_TripId_Trips");
        });

        modelBuilder.Entity<TripSeatInventory>(entity =>
        {
            entity.ToTable("TripSeatInventory");

            entity.HasIndex(e => new { e.TripId, e.Status }, "IX_TripSeatInventory_Trip_Status");

            entity.HasIndex(e => new { e.TripId, e.SeatLayoutSeatId }, "UX_TripSeatInventory_Trip_Seat").IsUnique();

            entity.Property(e => e.BlockedReason).HasMaxLength(255);
            entity.Property(e => e.DeckSnapshot)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SeatCodeSnapshot)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SeatTypeSnapshot)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.SeatLayoutSeat).WithMany(p => p.TripSeatInventories)
                .HasForeignKey(d => d.SeatLayoutSeatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripSeatInventory_SeatLayoutSeatId_SeatLayoutSeats");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripSeatInventories)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripSeatInventory_TripId_Trips");
        });

        modelBuilder.Entity<TripStaffAssignment>(entity =>
        {
            entity.Property(e => e.AssignedAtUtc).HasPrecision(3);
            entity.Property(e => e.ContactReleaseAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Conductor).WithMany(p => p.TripStaffAssignments)
                .HasForeignKey(d => d.ConductorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripStaffAssignments_ConductorId_Conductors");

            entity.HasOne(d => d.Driver).WithMany(p => p.TripStaffAssignments)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripStaffAssignments_DriverId_Drivers");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripStaffAssignments)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripStaffAssignments_TripId_Trips");
        });

        modelBuilder.Entity<TripStop>(entity =>
        {
            entity.HasIndex(e => new { e.RouteStopId, e.DepartureAtLocal }, "IX_TripStops_Stop_Departure");

            entity.HasIndex(e => new { e.TripId, e.SequenceNo }, "UX_TripStops_Trip_Sequence").IsUnique();

            entity.Property(e => e.ArrivalAtLocal).HasPrecision(3);
            entity.Property(e => e.BoardingAllowed).HasMaxLength(255);
            entity.Property(e => e.DepartureAtLocal).HasPrecision(3);
            entity.Property(e => e.DroppingAllowed).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.RouteStop).WithMany(p => p.TripStops)
                .HasForeignKey(d => d.RouteStopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripStops_RouteStopId_RouteStops");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripStops)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripStops_TripId_Trips");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "UX_Users_Email").IsUnique();

            entity.HasIndex(e => e.PhoneNumber, "UX_Users_PhoneNumber").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.PasswordHash).HasMaxLength(500);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.Property(e => e.AssignedAtUtc).HasPrecision(3);

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_RoleId_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_UserId_Users");
        });

        modelBuilder.Entity<UserTravelPreference>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}